.eslintrc.js, .gitignore, api/index.ts, index.ts, package-lock.json, package.json, src/order/index.ts, src/util/index.ts, tsconfig.json, types/Order.ts, types/index.ts
- Added initial configuration
- Defined function to fetch order details using solr-query on the basis of orderId
- Defined function to updated order status
- Added types support for order module
- Defined functions to update the token and instance url
=> Implemented: initial configuration for oms package and added support to fetch order details and update order status(#2ebeamz)

src/order/index.ts, src/product/index.ts
=> Updated: transformation library usage to directly use tranform method for mapping instead of creating DataTransform object(#2zgxazg)

src/api/index.ts
=> Implemented: action to clear all the initialized data using a single method

package-lock.json, package.json, release-notes.md
=> Updated: package version and release notes for new release

package-lock.json, package.json
=> Updated: package version to prepare for patch release

src/index.ts
Closes #31 
Exported the `resetConfig` method from the oms package to be used in an application.
=> Fixed: issue in using resetConfig by exporting it from the package(#85zrh2rvp)

package-lock.json, package.json, release-notes.md
=> Updated: version of package for patch release to 1.0.2

src/index.ts, src/modules/index.ts, src/modules/product/index.ts, src/product/index.ts
Unable to fetch the products as groups
Closes #18 
The defined method will help in fetching product information by grouping on a specific field
=> Implemented: method to fetch product information as groups and transform the response(#2z5ebhx)

package-lock.json, package.json
=> Updated: version in package and lock file for minor release

src/mappings/product.ts
Closes #34 
When displaying products there are some cases in which we need to display product identifications.
=> Implemented: support to return product identifications(#85zrh5n0c)

src/index.ts, src/modules/order/index.ts, src/modules/product/index.ts, src/types/index.ts
=> Implemented: enumeration for operators(#85zrhfydn)

package-lock.json, package.json, release-notes.md
=> Updated: version for app in package and lock file for minor release

README.md
=> Added: usage instructions in oms package(#85zrhxfvk)

package-lock.json, package.json, release-notes.md
=> Updated: package version and release notes for minor release

src/index.ts, src/modules/index.ts, src/modules/stock/index.ts
Closes #51 
Defined a method to fetch the stock sum on all the facilities for products
=> Implemented: support to fetch stock on all facilities for products(#85zrjdbhn)

package-lock.json, package.json, release-notes.md
=> Updated: version and release notes for minor release(v1.4.0)

package-lock.json, package.json, src/api/index.ts, src/modules/order/index.ts, src/modules/product/index.ts, src/modules/stock/index.ts
=> Implemented: support for using qs library for paramsSerializer(#85zrkt79g)

src/api/index.ts
=> Implemented: usage of params serializer in client method(#85zrkt79g)

package-lock.json, package.json, release-notes.md
=> Updated: package version and release notes for minor release v1.5.0

src/index.ts
=> Improved: code to expose the api and client method from oms api

package-lock.json, package.json, release-notes.md
=> Updated package version for patch release v1.5.1

package-lock.json, package.json, src/api/index.ts, src/index.ts
=> Implemented: support to make events and interceptors configurable (#61)

package-lock.json, package.json, release-notes.md
=> Updated: app version and release notes for minor release(v1.7.0)

src/index.ts, src/mappings/order.ts, src/modules/index.ts, src/modules/order/index.ts, src/modules/product/index.ts, src/modules/stock/index.ts, src/modules/user/index.ts, tsconfig.json
=> Implemented: support to get and set the product identifications(#85zt68k1k)

src/api/index.ts, src/index.ts, src/modules/index.ts, src/modules/user/index.ts
=> Implemented: support for logout api and added method to return the config passed from app

package-lock.json, package.json
=> Updated: package and lock file for minor release(v1.9.0)

src/index.ts, src/modules/index.ts, src/modules/user/index.ts
Closes #
Implemented: Added an API to fetch user's facilities.
=> Implemented: Added an api to fetch user's facilities.

src/index.ts, src/modules/index.ts, src/modules/notification/index.ts
=> Implemented: notifications module for firebase notifications support

package-lock.json, package.json
=> Updated: package version for minor release (1.10.0)

src/index.ts, src/modules/index.ts, src/modules/user/index.ts
=> Implemented: usage of setLocale API

package-lock.json, package.json
Closes #
Updated: Version for the minor release (1.11.0).
=> Updated: Version for the minor release (1.11.0).

src/modules/notification/index.ts
Related Issue: https://github.com/hotwax/bopis/issues/274
Improved payload for fetching user preferred notification preference based on current user.
=> Improved: logic to fetch user preferred notification preferences (bopis-274)

package-lock.json, package.json
=> Updated: app version for patch release(v1.11.1)

package-lock.json, package.json
=> Updated: package and lock file for minor release(v1.13.0)

src/index.ts, src/modules/index.ts, src/modules/user/index.ts
Related Issue https://github.com/hotwax/dxp-components/issues/139
=> Implemented: apis to get and set timeZone of the user(dxp/139)

package-lock.json, package.json
=> Improved: version in package and lock file for minor relase(v1.14.0)

src/api/index.ts, src/index.ts, src/modules/gitbook/index.ts, src/modules/index.ts
Closes #
Implemented centralized services to call gitbook api.
=> Implemented: centralized services for Gitbook api calls

src/modules/product/index.ts
#88 
Closes #
Improved: Used POST method instead of GET for solr-query endPoint.
=> Improved: Used POST mehtod instead of GET for solr-query endPoint (#88).

package-lock.json, package.json
=> Updated: app version for patch release v1.15.1.

src/index.ts, src/modules/index.ts, src/modules/user/index.ts, src/util/index.ts
Closes https://github.com/hotwax/dxp-components/issues/193
- Added  `getEComStores` API to fetch stores based on facilityId or without it.
- Added `setEComStore` api for setting the ECom store.
- Used the `getUserPreference` API to retrieve the preferred store.
=> Implemented: API calls to get user preferred store and ecom stores in user module(#193)

src/index.ts, src/modules/index.ts, src/modules/product/index.ts
#91 
Closes #
Implemented: Added api to fetch good identification types (#91).
=> Implemented: Added api to fetch good identification types (#91).

package-lock.json, package.json
=> Updated: oms-api version for the minor release v1.16.0

src/index.ts, src/modules/index.ts, src/modules/user/index.ts
#94 
- Added an API that fetches and returns all product stores irrespective of the facility.  
- It only takes `vSize`, which is an optional parameter with a default value of 100.
=> Implemented: Added support for fetching all ECom stores irrespective of any parameters (#94)

package-lock.json, package.json
=> Improved: package version in package and lock file for minor release(v1.17.0)

src/modules/notification/index.ts
https://github.com/hotwax/bopis/issues/510
Added filterConditions map, so to allow method call to override/add some extra conditions.
=> Fixed: notification fetching logic to fetch specific notifications(bopis/510)

package-lock.json, package.json
=> Improved: package version in package and lock file for patch release(v1.17.1)

package-lock.json, package.json
- Updated the package version of oms-api in package and lock file for minor release(v1.18.0)
=> Improved: package version in package and lock file for minor release(v1.18.0)

src/modules/index.ts, src/modules/product/index.ts, src/modules/product/moquiIndex.ts, src/modules/user/index.ts, src/modules/user/moquiIndex.ts
#101
Implemented logic for alternative api calls to moqui for performing same action as ofbiz one for Dxp-components.
=> Implemented: support for fetching moqui api's for needed data for dxp-components in moqui based apps (#101)

src/modules/index.ts, src/modules/user/index.ts, src/modules/user/moquiIndex.ts
https://github.com/hotwax/dxp-components/issues/393
- Updated the structure of fetching and updating product store setting.
- Updated the parameters strucutre of code internally.
=> Improved: structure of methods for proper parameter passing, updated structure of product store setting methods (dxp-393)

package-lock.json, package.json
=> Updated: package and lock file for minor release(v1.20.0)

src/modules/user/index.ts
=> Improved: support to fetch facility type as well when fetching facilities(fulfillment/1212)

package-lock.json, package.json
=> Improved: app version in package and lock file for minor release(v1.21.0)

src/api/index.ts, src/modules/user/moquiIndex.ts
Replaced the api_key with the authorization header , for maarg api call.
#114
=> Improved: Replaced api_key to Authorization header

package-lock.json, package.json
=> Improved: app version in package and lock file for minor release(v1.23.0)

src/api/index.ts, src/modules/index.ts, src/modules/notification/index.ts, src/modules/notification/moquiIndex.ts, src/modules/user/moquiIndex.ts
=> Used updated maarg end points for CRUD(#118)

src/modules/index.ts, src/modules/user/index.ts, src/modules/user/moquiIndex.ts
=> Added: Maarg endpoints to update user timeZone and locale

src/index.ts, src/modules/index.ts, src/modules/user/moquiIndex.ts
Changelog: Added
Related Issue: #121
=> Added App Bridge Maarg Login API

package-lock.json, package.json
=> Updated: oms-api package version for the minor release 1.26.0

src/api/index.ts
=> Implemented: response error interceptor for handling the auth errors

src/modules/user/moquiIndex.ts
Closes #
Fixed: Fetched all the facilities of the passed facility group for the admin user.
=> Fixed: Fetched all the facilities of the passed facility group for the admin user.
